Release/3.6.0 (#8)
ci: ajustar condição de publicação da versão stable no nuget.org

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,7 +17,7 @@ jobs:
     steps:
       - uses: actions/checkout@v5
 
-      - name: Display workflow envs
+      - name: Display github actions variables
         run: |
           echo "GITHUB_REF: $GITHUB_REF"
           echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
@@ -26,6 +26,56 @@ jobs:
           echo "GITHUB_SHA: $GITHUB_SHA"
           echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
           echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
+          
+      - name: "Determine version: preview - Publish release branch"
+        id: version-preview
+        if: startsWith(github.ref_name, 'release/')
+        run: |
+          # Obtém o prefixo da versão a partir do nome do branch de release
+          VERSION_PREFIX="${GITHUB_REF_NAME##*/}"          
+          VERSION_SUFFIX="preview-${GITHUB_RUN_NUMBER}"
+          
+          echo "VERSION_PREFIX: $VERSION_PREFIX"
+          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
+          
+          echo "version_determined=true" >> $GITHUB_OUTPUT
+          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
+          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
+
+      - name: "Determine version: stable - Publish main branch, after release pull request is merged"
+        id: version-stable
+        if: |
+          github.event_name == 'pull_request' &&
+          github.base_ref == 'main' &&
+          startsWith(github.head_ref, 'release/') &&
+          github.event.pull_request.merged == true
+        run: |
+          # Obtém o prefixo da versão a partir do nome do branch de origem do pull request
+          VERSION_PREFIX="${GITHUB_HEAD_REF##*/}"          
+          VERSION_SUFFIX=""
+          
+          echo "VERSION_PREFIX: $VERSION_PREFIX"
+          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
+          
+          echo "version_determined=true" >> $GITHUB_OUTPUT
+          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
+          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
+
+      - name: Abort if version was indeterminate
+        if: steps.version-preview.outputs.version_determined == '' && steps.version-stable.outputs.version_determined == ''
+        uses: actions/github-script@v8
+        with:
+          script: core.setFailed("Version could not be determined to branch workflow.");
+
+      - name: Validate determined version prefix with csproj file # Validação de segurança
+        run: |
+          CSPROJ_VERSION_PREFIX=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" src/Version.props)
+          echo "CSPROJ_VERSION_PREFIX: $CSPROJ_VERSION_PREFIX"
+          
+          if [ "$CSPROJ_VERSION_PREFIX" != "$VERSION_PREFIX" ]; then
+            echo "::error::Version prefix in csproj file ($CSPROJ_VERSION_PREFIX) does not match witch the determined version prefix from branch name ($VERSION_PREFIX)."
+            exit 1
+          fi
 
       - name: Setup .NET
         uses: actions/setup-dotnet@v5
@@ -41,46 +91,6 @@ jobs:
       - name: Test
         run: dotnet test --configuration Release --no-build
 
-      - name: Determine version (preview) - To release branch publish
-        if: startsWith(github.ref_name, 'release/')
-        run: |
-          # Obtém o prefixo da versão a partir do nome do branch de release
-          VERSION_PREFIX="${GITHUB_REF_NAME##*/}"          
-          VERSION_SUFFIX="preview-${GITHUB_RUN_NUMBER}"
-          
-          echo "VERSION_PREFIX: $VERSION_PREFIX"
-          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
-          
-          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
-          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
-
-      - name: Determine version (stable) - To main branch publish from release pull request
-        if: |
-          github.event_name == 'pull_request' &&
-          github.base_ref == 'main' &&
-          github.event.pull_request.merged == true &&
-          startsWith(github.head_ref, 'release/')
-        run: |
-          # Obtém o prefixo da versão a partir do nome do branch de origem do pull request
-          VERSION_PREFIX="${GITHUB_HEAD_REF##*/}"          
-          VERSION_SUFFIX=""
-          
-          echo "VERSION_PREFIX: $VERSION_PREFIX"
-          echo "VERSION_SUFFIX: $VERSION_SUFFIX"
-          
-          echo "VERSION_PREFIX=$VERSION_PREFIX" >> $GITHUB_ENV
-          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
-
-      - name: Validate determined version prefix with csproj file # Validação de segurança
-        run: |
-          CSPROJ_VERSION_PREFIX=$(grep -oPm1 "(?<=<VersionPrefix>)[^<]+" src/Version.props)
-          echo "CSPROJ_VERSION_PREFIX: $CSPROJ_VERSION_PREFIX"
-          
-          if [ "$CSPROJ_VERSION_PREFIX" != "$VERSION_PREFIX" ]; then
-            echo "Version prefix in csproj file ($CSPROJ_VERSION_PREFIX) does not match the determined version suffix ($VERSION_PREFIX)"
-            exit 1
-          fi
-
       - name: Pack
         run: dotnet pack src/Extensions.csproj --configuration Release --no-build -p:VersionPrefix="$VERSION_PREFIX" -p:VersionSuffix="$VERSION_SUFFIX"
 
@@ -90,10 +100,13 @@ jobs:
           name: nuget-package
           path: src/bin/Release/*.nupkg
 
-      - name: Publish release preview to MyGet
+      - name: Publish version to MyGet (preview)
         run: dotnet nuget push src/bin/Release/*.nupkg --source https://www.myget.org/F/maestrianet/api/v3/index.json --api-key "${{ secrets.MYGET_API_KEY }}"
 
-      - name: Publish to NuGet
-        if: startsWith(github.ref, 'refs/tags/')
-        run: |
-          dotnet nuget push src/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
+      - name: Publish version to NuGet (stable)
+        if: |
+          github.event_name == 'pull_request' &&
+          github.base_ref == 'main' &&
+          startsWith(github.head_ref, 'release/') &&
+          github.event.pull_request.merged == true
+        run: dotnet nuget push src/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
